### ISSUE TITLE
Crash when using it on Fabric 1.16.5

### ISSUE THREAD

**Issue by remidu64** [Ran-Mewo/UwU#2]
when I try to boot up the game, it crashes and Fabric shows me this:
(Showing the full error since it's short)

Uncaught exception in thread "main"
java.lang.UnsupportedClassVersionError: fabric/io/github/ran/qwikse/fabric/QwikseLoader has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setupLanguageAdapters(FabricLoaderImpl.java:439)
	at net.fabricmc.loader.impl.FabricLoaderImpl.finishModLoading(FabricLoaderImpl.java:349)
	at net.fabricmc.loader.impl.FabricLoaderImpl.freeze(FabricLoaderImpl.java:112)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:149)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
----------------------------------------------------------------------------------------------------------------------------------------------------

I've already seen that it might be related to my JRE.
I'm using Java 8 GraalVM Enterprise Edition with these arguments:
-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:+AlwaysActAsServerClassMachine -XX:+ParallelRefProcEnabled -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -XX:AllocatePrefetchStyle=1 -XX:ThreadPriorityPolicy=1 -XX:+UseNUMA -XX:+UseDynamicNumberOfGCThreads -XX:NmethodSweepActivity=1 -XX:ReservedCodeCacheSize=350M -XX:-DontCompileHugeMethods -XX:MaxNodeLimit=240000 -XX:NodeLimitFudgeFactor=8000 -XX:+UseFPUForSpilling -XX:+EnableJVMCI -XX:+UseJVMCICompiler -XX:+EagerJVMCI -Dgraal.TuneInlinerExploration=1 -Dgraal.CompilerConfiguration=enterprise -Dgraal.UsePriorityInlining=true -Dgraal.Vectorization=true -Dgraal.OptDuplication=true -Dgraal.DetectInvertedLoopsAsCounted=true -Dgraal.LoopInversion=true -Dgraal.VectorizeHashes=true -Dgraal.EnterprisePartialUnroll=true -Dgraal.VectorizeSIMD=true -Dgraal.StripMineNonCountedLoops=true -Dgraal.SpeculativeGuardMovement=true -Dgraal.InfeasiblePathCorrelation=true

**Comment by remidu64** [comment]
I think I have found the problem by myself: I'm using Java 8 and this mod requires Java 17
The thing is that 1.16.5 runs in Java 8 so the 1.16.5 version of the mod can't work unless you rewrite it using Java 8

**Comment by Ran-Mewo** [comment]
I forgor that 1.16.5 can run on java 8
why not install java 17 and run 1.16.5?

**Comment by remidu64** [comment]
The JVM crashes instantly on 1.16.5

**Comment by Ran-Mewo** [comment]
weird but I run 1.16.5 on java 17
anyways I'll get uwu mod compiling for java 8 for 1.16.5 soon:tm:

**Comment by remidu64** [comment]
How did you get 1.16.5 to run on Java 17 ?

**Comment by Ran-Mewo** [comment]
I use java 17 graalvm enterprise edition
It works for me?

**Comment by remidu64** [comment]
I use the same exact same thing

**Comment by remidu64** [comment]
I guess it might related to the JVM arguments I use

**Comment by remidu64** [comment]
What JVM arguments do you use ?

Edit: Nevermind, the mod shows me the exact same error when I try to load it up with MC 1.16.5 Fabric on Java 17 (And it was the JVM arguments that were crashing the JVM)

**Comment by Ran-Mewo** [comment]
Also I believe there's an old 1.16.5 that should work

**Comment by remidu64** [comment]
I switched from Graalvm EE to Adoptium OpenJRE and it works.
