### ISSUE TITLE
1.16.5 Forge java 8 Error initialising mixin config forge-uwu-common.mixins.json

### ISSUE THREAD

**Issue by vsaucing** [Ran-Mewo/UwU#5]
i play 1.16.5 with forge
this mod crashes mc
log;:
PolyMC version: 1.2.2-d12e3df4

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.245.31.108, 18.245.31.124, 18.245.31.14, 18.245.31.84]

session.minecraft.net resolves to:
    [2620:1ec:bdf::45, 2620:1ec:46::45, 13.107.213.45, 13.107.246.45]

textures.minecraft.net resolves to:
    [2620:1ec:bdf::45, 2620:1ec:46::45, 13.107.246.45, 13.107.213.45]

api.mojang.com resolves to:
    [2620:1ec:46::45, 2620:1ec:bdf::45, 13.107.213.45, 13.107.246.45]

Minecraft folder is:
C:/Users/memir/AppData/Roaming/PolyMC/instances/1.16.5/.minecraft

Java path is:
C:/Program Files/Java/jre-1.8/bin/javaw.exe

Checking Java version...
Java is version 1.8.0_391, using amd64 architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/memir/AppData/Roaming/PolyMC/instances/1.16.5/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc2/ForgeWrapper-mmc2.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/forge/1.16.5-36.2.34/forge-1.16.5-36.2.34-launcher.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/cpw/mods/modlauncher/8.1.3/modlauncher-8.1.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/cpw/mods/grossjava9hacks/1.3.3/grossjava9hacks-1.3.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/accesstransformers/3.0.1/accesstransformers-3.0.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/eventbus/4.0.0/eventbus-4.0.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/forgespi/3.2.0/forgespi-3.2.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/coremods/4.0.6/coremods-4.0.6.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/electronwill/night-config/core/3.6.3/core-3.6.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/electronwill/night-config/toml/3.6.3/toml-3.6.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/net/minecraftforge/nashorn-core-compat/15.1.1.1/nashorn-core-compat-15.1.1.1.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/memir/AppData/Roaming/PolyMC/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔️] auudio_forge_1.0.3-1_MC_1.16.2-1.16.5
  [✔️] betterf3-1.16.5-1.0
  [✔️] BetterF3-1.5.0-Forge-1.16.5
  [✔️] Bookshelf-Forge-1.16.5-10.4.33
  [✔️] Chunky-1.2.123
  [✔️] cloth-config-4.17.101-forge
  [✔️] CrosshairBobbing-1.2
  [✔️] DripSounds-1.16-0.3.0
  [✔️] elytrautilities-forge-1.16.5-0.0.1
  [✔️] EnableMultiPlayerMode-1.0.0+Forge1.16.X
  [✔️] enchlevel-langpatch-2.1.2
  [✔️] entityculling-forge-mc1.16.5-1.5.2
  [✔️] Fallingleaves-1.16.3-1.2.2
  [✔️] fancymenu_forge_2.14.9_MC_1.16.2-1.16.5
  [✔️] ferritecore-2.1.1-forge
  [✔️] fm_audio_extension_forge_1.1.1_MC_1.16.2-1.16.5
  [❌] foodeffecttooltips-1.0.0+forge-1.16.5.jar (disabled)
  [✔️] FPS-Monitor-1.16.5-1.2.1
  [✔️] GameMenuModOption-1.16.4-1.8.2
  [✔️] IdleTweaks-1.0.6
  [✔️] Jade-1.16.4-2.8.3
  [✔️] jeed-1.16.5-1.6
  [✔️] jei-1.16.5-7.8.0.1011
  [✔️] konkrete_forge_1.6.1_MC_1.16.2-1.16.5
  [✔️] kontrolo-1.4.0
  [✔️] kotlinforforge-1.17.0-obf
  [✔️] lightspeed-1.16.5-1.0.5
  [✔️] loadmyresources_forge_1.0.4_MC_1.16.2-1.16.5
  [✔️] memoryleakfix-forge-pre1.17-1.1.5
  [✔️] missiles-0.1
  [✔️] mobhealthbar-forge-1.16.5-2.2.0
  [✔️] modernfix-forge-5.13.0+mc1.16.5
  [✔️] OptiFine_1.16.5_HD_U_G8
  [✔️] refinedstorage-1.9.18
  [✔️] Rrls-1.5.1-forge
  [✔️] saturn-mc1.16.5-0.0.3
  [✔️] Squake-1.16.5-16.1.1
  [✔️] Tips-1.16.5-4.0.18
  [✔️] TravelersBackpack-1.16.5-5.4.51
  [✔️] uwu-1.5-1.16.5
  [✔️] veinmining-forge-1.16.5-0.18
  [✔️] Xaeros_Minimap_23.9.7_Forge_1.16.5

Params:
  --username  --version PolyMC --gameDir C:/Users/memir/AppData/Roaming/PolyMC/instances/1.16.5/.minecraft --assetsDir C:/Users/memir/AppData/Roaming/PolyMC/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release --launchTarget fmlclient --fml.forgeVersion 36.2.34 --fml.mcVersion 1.16.5 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20210115.111550

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms3072m, -Xmx3072m, -Duser.language=en]

Minecraft process ID: 316

Feb 12, 2024 5:23:49 PM org.multimc.EntryPoint parseLine
INFO: Using onesix launcher.
Checking: MC_SLIM
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: PATCHED
Checking: MC_SRG
2024-02-12 17:23:53,955 main WARN Advanced terminal features are not available in this environment
[17:23:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, EmirPro876, --version, PolyMC, --gameDir, C:/Users/memir/AppData/Roaming/PolyMC/instances/1.16.5/.minecraft, --assetsDir, C:/Users/memir/AppData/Roaming/PolyMC/assets, --assetIndex, 1.16, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, <ACCESS TOKEN>, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.34, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[17:23:54] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 1.8.0_391 by Oracle Corporation
[17:23:55] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[17:23:55] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\memir\AppData\Roaming\PolyMC\instances\1.16.5\.minecraft\mods\OptiFine_1.16.5_HD_U_G8.jar
[17:23:55] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[17:23:56] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[17:23:56] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/memir/AppData/Roaming/PolyMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[17:23:56] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[17:23:59] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[17:23:59] [main/INFO] [op.OptiFineTransformer/]: Targets: 311
[17:24:00] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[17:24:00] [main/ERROR] [mixin/]: Mixin config mixin.xbob.json does not specify "minVersion" property
Feb 12, 2024 5:24:00 PM org.multimc.onesix.OneSixLauncher launchWithMainClass
SEVERE: Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:217)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:252)
	at org.multimc.EntryPoint.listen(EntryPoint.java:124)
	at org.multimc.EntryPoint.main(EntryPoint.java:39)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57)
	... 8 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config forge-uwu-common.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addConfig(MixinPlatformManager.java:262)
	at org.spongepowered.asm.launch.platform.MixinPlatformAgentDefault.prepare(MixinPlatformAgentDefault.java:46)
	at org.spongepowered.asm.launch.platform.MixinContainer.prepare(MixinContainer.java:122)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.createContainerFor(MixinPlatformManager.java:144)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addContainer(MixinPlatformManager.java:134)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.addNestedContainers(MixinPlatformManager.java:152)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.scanForContainers(MixinPlatformManager.java:213)
	at org.spongepowered.asm.launch.platform.MixinPlatformManager.inject(MixinPlatformManager.java:186)
	at org.spongepowered.asm.launch.MixinBootstrap.inject(MixinBootstrap.java:202)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:201)
	at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.initializeLaunch(MixinLaunchPluginLegacy.java:195)
	at cpw.mods.modlauncher.LaunchPluginHandler.lambda$announceLaunch$9(LaunchPluginHandler.java:97)
	at java.util.HashMap.forEach(Unknown Source)
	at cpw.mods.modlauncher.LaunchPluginHandler.announceLaunch(LaunchPluginHandler.java:97)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:52)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	... 13 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.1 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:555)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:500)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:428)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1285)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 33 more

Feb 12, 2024 5:24:00 PM org.multimc.EntryPoint main
INFO: Exiting with -1
İşlem şu kod ile bitti: -1.
Clipboard copy at: 12 Feb 2024 17:28:10 +0300

**Comment by Ran-Mewo** [comment]
Ah oops I forgot about supporitng Java 8 for 1.16.5 players
I'll push a fix soon but you should consider updating your Java version imo

**Comment by vsaucing** [comment]
I updated it but an other mod crashes with it
